'use strict';

// tests for createUser
// Generated by serverless-jest-plugin

const mod = require('./../functions/createUser');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'createUser' });

describe('createUser', () => {
  beforeAll((done) => {
  //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('Creates a new user', async () => {
    const response = await wrapped.run({});
    expect(response).toBeDefined();
  });
});

